# Generated by Django 4.1.4 on 2022-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_rename_author_proposal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
